import { createErrorHandlers } from "./lib/error/error-handler";
import { createHolidaysHandlers } from "./lib/holidays/holidays-handlers";
import { createMediaHandlers } from "./lib/media/media-handler";
import { createMenuHandlers } from "./lib/menu/menu-handlers.ts";
import { createMessagesHandlers } from "./lib/messages/messages-handlers";
import { createRedditHandlers } from "./lib/reddit/reddit-handlers";
import { createRequestHandlers } from "./lib/request/request-handlers";
import { createSettingsHandlers } from "./lib/settings/settings-handlers";
import { createSettingsTunnelHandlers } from "./lib/settings/settings-tunnel-handlers";
import { createStihiRuHandlers } from "./lib/stihiru/stihiru-handlers";
import { createTelegramHandlers } from "./lib/telegram";
import { createYaPlakalHandlers } from "./lib/yaplakal/yaplakal-handlers";

export const menuAPI = createMenuHandlers();
export const requestsAPI = createRequestHandlers();
export const messagesAPI = createMessagesHandlers();
export const settingsAPI = createSettingsHandlers();
export const stihiRuAPI = createStihiRuHandlers();
export const tunnelAPI = createSettingsTunnelHandlers();
export const yapAPI = createYaPlakalHandlers();
export const errorAPI = createErrorHandlers();
export const mediaAPI = createMediaHandlers();
export const telegramAPI = createTelegramHandlers();
export const redditAPI = createRedditHandlers();
export const holidaysAPI = createHolidaysHandlers();
