import { createErrorHandlers } from "@preload/lib/error/error-handler";
import { createHolidaysHandlers } from "@preload/lib/holidays/holidays-handlers";
import { createMediaHandlers } from "@preload/lib/media/media-handler";
import { createMenuHandlers } from "@preload/lib/menu/menu-handlers.ts";
import { createMessagesHandlers } from "@preload/lib/messages/messages-handlers";
import { createRedditHandlers } from "@preload/lib/reddit/reddit-handlers";
import { createRequestHandlers } from "@preload/lib/request/request-handlers";
import { createSettingsHandlers } from "@preload/lib/settings/settings-handlers";
import { createSettingsTunnelHandlers } from "@preload/lib/settings/settings-tunnel-handlers";
import { createStihiRuHandlers } from "@preload/lib/stihiru/stihiru-handlers";
import { createTelegramHandlers } from "@preload/lib/telegram";
import { createYaPlakalHandlers } from "@preload/lib/yaplakal/yaplakal-handlers";

export const menuAPI = createMenuHandlers();
export const requestsAPI = createRequestHandlers();
export const messagesAPI = createMessagesHandlers();
export const settingsAPI = createSettingsHandlers();
export const stihiRuAPI = createStihiRuHandlers();
export const tunnelAPI = createSettingsTunnelHandlers();
export const yapAPI = createYaPlakalHandlers();
export const errorAPI = createErrorHandlers();
export const mediaAPI = createMediaHandlers();
export const telegramAPI = createTelegramHandlers();
export const redditAPI = createRedditHandlers();
export const holidaysAPI = createHolidaysHandlers();
